version: '3'

services:
  ttyd:
    build: ./
    image: ttyd:latest
    expose:
      - 7681
    environment:
      T_CONF_DIR: /root/.config/tmuxinator
      EDITOR: vim
    volumes:
      - ~/.config/tmuxinator/:/root/.config/tmuxinator/
      - ~/.ssh:/root/.ssh
      - ./files/default.yml:/root/.config/tmuxinator/default.yml
      - ./files/vimrc:/root/.vimrc
      - ./files/tmux.conf:/root/.tmux.conf
    entrypoint:
      - ttyd
      - --url-arg
      - /usr/local/bin/tmuxinator.sh
    ports:
      - 0.0.0.0:80:7681
