name: <%= name %>
root: ~/

startup_window: <%= name %>

windows:
  - config:
      panes:
        - tmuxinator edit <%= name %>
  - <%= name %>:
      pre:
      panes:
        - 
          -
          -
        -
          -
          -
